language: node_js

node_js:
  - "iojs"
  - "4"
  - "5"
  - "6"

sudo: false

addons:
  apt:
    packages:
      - xvfb

cache:
  directories:
    - node_modules

notifications:
  email: false

before_script:
  - export DISPLAY=:99.0
  - Xvfb :99 -screen 0 1024x768x24 +extension RANDR >/dev/null 2>&1 &
